apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nutrismart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName non défini = utilise le StorageClass par défaut du cluster
  # (local-path pour k3s, standard pour kind)
