import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName = `${geistSans.variable} ${geistMono.variable} antialiased`;

  // Some browser extensions inject attributes on <body> before React hydrates,
  // so we suppress those false-positive mismatch warnings at the root.
  return (
    <html lang="en">
      <body suppressHydrationWarning className={bodyClassName}>
        {children}
      </body>
    </html>
  );
}
